/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dimen_jni_PusherNative */

#ifndef _Included_com_dimen_jni_PusherNative
#define _Included_com_dimen_jni_PusherNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dimen_jni_PusherNative
 * Method:    startPush
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dimen_jni_PusherNative_startPush
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dimen_jni_PusherNative
 * Method:    stopPush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dimen_jni_PusherNative_stopPush
  (JNIEnv *, jobject);

/*
 * Class:     com_dimen_jni_PusherNative
 * Method:    realease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dimen_jni_PusherNative_realease
  (JNIEnv *, jobject);

/*
 * Class:     com_dimen_jni_PusherNative
 * Method:    setVideoOptions
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_dimen_jni_PusherNative_setVideoOptions
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_dimen_jni_PusherNative
 * Method:    setAudioOptions
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_dimen_jni_PusherNative_setAudioOptions
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_dimen_jni_PusherNative
 * Method:    fireVideo
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_dimen_jni_PusherNative_fireVideo
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_dimen_jni_PusherNative
 * Method:    fireAudio
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_dimen_jni_PusherNative_fireAudio
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
